# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='textbook',
            old_name='id',
            new_name='uuid',
        ),
    ]
