# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson', models.IntegerField(default=1)),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Textbook')),
            ],
        ),
    ]
