# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.TextField(max_length=500)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.Note')),
            ],
        ),
    ]
